version: 0.2
phases:
  build:
    commands:
      - sleep 3
      - git status
      - COMMIT=$(git log -n 1 --pretty | grep commit | cut -d' ' -f 2)
      - echo $COMMIT
      - git branch --contains $COMMIT
