version: 0.2
phases:
  build:
    commands:
      - echo "Building all projects"
      - ls ./go | xargs -I % sh -c 'go build %;'
  post_build:
    commands:
      - echo "Executing project binaries"
      - ls ./go | grep -v ".go" | xargs -I % /bin/bash -c "echo % && ./% && echo";
